name: thbeer
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  salomon_bottom_bar: ^3.3.2
  quran: ^1.2.3
  google_fonts: ^6.1.0
  flutter_animate: ^4.4.1
  flutter_svg: ^2.0.9
  flutter_sound: ^9.2.13
  permission_handler: ^11.2.0
  awesome_extensions: ^2.0.12
  star_menu: ^3.1.5
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
  - assets/
